#include "flags.h"
FlagEntry LuaGuiWindowFlags[] = {
        {"ImGuiWindowFlags_None", ImGuiWindowFlags_None},
        {"ImGuiWindowFlags_NoTitleBar", ImGuiWindowFlags_NoTitleBar},
        {"ImGuiWindowFlags_NoResize",               ImGuiWindowFlags_NoResize},
        {"ImGuiWindowFlags_NoMove",                 ImGuiWindowFlags_NoMove},
        {"ImGuiWindowFlags_NoScrollbar",            ImGuiWindowFlags_NoScrollbar},
        {"ImGuiWindowFlags_NoScrollWithMouse",      ImGuiWindowFlags_NoScrollWithMouse},
        {"ImGuiWindowFlags_NoCollapse",             ImGuiWindowFlags_NoCollapse},
        {"ImGuiWindowFlags_AlwaysAutoResize",       ImGuiWindowFlags_AlwaysAutoResize},
        {"ImGuiWindowFlags_NoBackground",           ImGuiWindowFlags_NoBackground},
        {"ImGuiWindowFlags_NoSavedSettings",        ImGuiWindowFlags_NoSavedSettings},
        {"ImGuiWindowFlags_NoMouseInputs",          ImGuiWindowFlags_NoMouseInputs},
        {"ImGuiWindowFlags_MenuBar",                 ImGuiWindowFlags_MenuBar},
        {"ImGuiWindowFlags_HorizontalScrollbar",    ImGuiWindowFlags_HorizontalScrollbar},
        {"ImGuiWindowFlags_NoFocusOnAppearing",     ImGuiWindowFlags_NoFocusOnAppearing},
        {"ImGuiWindowFlags_NoBringToFrontOnFocus",  ImGuiWindowFlags_NoBringToFrontOnFocus},
        {"ImGuiWindowFlags_AlwaysVerticalScrollbar",ImGuiWindowFlags_AlwaysVerticalScrollbar},
        {"ImGuiWindowFlags_AlwaysHorizontalScrollbar", ImGuiWindowFlags_AlwaysHorizontalScrollbar},
        {"ImGuiWindowFlags_NoNavInputs",             ImGuiWindowFlags_NoNavInputs},
        {"ImGuiWindowFlags_NoNavFocus",              ImGuiWindowFlags_NoNavFocus},
        {"ImGuiWindowFlags_UnsavedDocument",         ImGuiWindowFlags_UnsavedDocument},

        {"ImGuiWindowFlags_NoNav",                    ImGuiWindowFlags_NoNav},
        {"ImGuiWindowFlags_NoDecoration",             ImGuiWindowFlags_NoDecoration},
        {"ImGuiWindowFlags_NoInputs",                  ImGuiWindowFlags_NoInputs},

        {"ImGuiWindowFlags_ChildWindow",              ImGuiWindowFlags_ChildWindow},
        {"ImGuiWindowFlags_Tooltip",                   ImGuiWindowFlags_Tooltip},
        {"ImGuiWindowFlags_Popup",                     ImGuiWindowFlags_Popup},
        {"ImGuiWindowFlags_Modal",                     ImGuiWindowFlags_Modal},
        {"ImGuiWindowFlags_ChildMenu",                 ImGuiWindowFlags_ChildMenu},
};

FlagEntry LuaGuiChildFlags[] = {
        {"ImGuiChildFlags_None", ImGuiChildFlags_None},
        {"ImGuiChildFlags_Borders", ImGuiChildFlags_Borders},
        {"ImGuiChildFlags_AlwaysUseWindowPadding", ImGuiChildFlags_AlwaysUseWindowPadding},
        {"ImGuiChildFlags_ResizeX", ImGuiChildFlags_ResizeX},
        {"ImGuiChildFlags_ResizeY", ImGuiChildFlags_ResizeY},
        {"ImGuiChildFlags_AutoResizeX", ImGuiChildFlags_AutoResizeX},
        {"ImGuiChildFlags_AutoResizeY", ImGuiChildFlags_AutoResizeY},
        {"ImGuiChildFlags_AlwaysAutoResize", ImGuiChildFlags_AlwaysAutoResize},
        {"ImGuiChildFlags_FrameStyle", ImGuiChildFlags_FrameStyle},
        {"ImGuiChildFlags_NavFlattened", ImGuiChildFlags_NavFlattened},
};

FlagEntry LuaGuiItemFlags[] = {
        {"ImGuiItemFlags_None", ImGuiItemFlags_None},
        {"ImGuiItemFlags_NoTabStop", ImGuiItemFlags_NoTabStop},
        {"ImGuiItemFlags_NoNav", ImGuiItemFlags_NoNav},
        {"ImGuiItemFlags_NoNavDefaultFocus", ImGuiItemFlags_NoNavDefaultFocus},
        {"ImGuiItemFlags_ButtonRepeat", ImGuiItemFlags_ButtonRepeat},
        {"ImGuiItemFlags_AutoClosePopups", ImGuiItemFlags_AutoClosePopups},
        {"ImGuiItemFlags_AllowDuplicateId", ImGuiItemFlags_AllowDuplicateId},
};

FlagEntry LuaGuiInputTextFlags[] = {
        {"ImGuiInputTextFlags_None", ImGuiInputTextFlags_None},
        {"ImGuiInputTextFlags_CharsDecimal", ImGuiInputTextFlags_CharsDecimal},
        {"ImGuiInputTextFlags_CharsHexadecimal", ImGuiInputTextFlags_CharsHexadecimal},
        {"ImGuiInputTextFlags_CharsScientific", ImGuiInputTextFlags_CharsScientific},
        {"ImGuiInputTextFlags_CharsUppercase", ImGuiInputTextFlags_CharsUppercase},
        {"ImGuiInputTextFlags_CharsNoBlank", ImGuiInputTextFlags_CharsNoBlank},
        {"ImGuiInputTextFlags_AllowTabInput", ImGuiInputTextFlags_AllowTabInput},
        {"ImGuiInputTextFlags_EnterReturnsTrue", ImGuiInputTextFlags_EnterReturnsTrue},
        {"ImGuiInputTextFlags_EscapeClearsAll", ImGuiInputTextFlags_EscapeClearsAll},
        {"ImGuiInputTextFlags_CtrlEnterForNewLine", ImGuiInputTextFlags_CtrlEnterForNewLine},
        {"ImGuiInputTextFlags_ReadOnly", ImGuiInputTextFlags_ReadOnly},
        {"ImGuiInputTextFlags_Password", ImGuiInputTextFlags_Password},
        {"ImGuiInputTextFlags_AlwaysOverwrite", ImGuiInputTextFlags_AlwaysOverwrite},
        {"ImGuiInputTextFlags_AutoSelectAll", ImGuiInputTextFlags_AutoSelectAll},
        {"ImGuiInputTextFlags_ParseEmptyRefVal", ImGuiInputTextFlags_ParseEmptyRefVal},
        {"ImGuiInputTextFlags_DisplayEmptyRefVal", ImGuiInputTextFlags_DisplayEmptyRefVal},
        {"ImGuiInputTextFlags_NoHorizontalScroll", ImGuiInputTextFlags_NoHorizontalScroll},
        {"ImGuiInputTextFlags_NoUndoRedo", ImGuiInputTextFlags_NoUndoRedo},
        {"ImGuiInputTextFlags_ElideLeft", ImGuiInputTextFlags_ElideLeft},
        {"ImGuiInputTextFlags_CallbackCompletion", ImGuiInputTextFlags_CallbackCompletion},
        {"ImGuiInputTextFlags_CallbackHistory", ImGuiInputTextFlags_CallbackHistory},
        {"ImGuiInputTextFlags_CallbackAlways", ImGuiInputTextFlags_CallbackAlways},
        {"ImGuiInputTextFlags_CallbackCharFilter", ImGuiInputTextFlags_CallbackCharFilter},
        {"ImGuiInputTextFlags_CallbackResize", ImGuiInputTextFlags_CallbackResize},
        {"ImGuiInputTextFlags_CallbackEdit", ImGuiInputTextFlags_CallbackEdit},
};

FlagEntry LuaGuiTreeNodeFlags[] = {
        {"ImGuiTreeNodeFlags_None", ImGuiTreeNodeFlags_None},
        {"ImGuiTreeNodeFlags_Selected", ImGuiTreeNodeFlags_Selected},
        {"ImGuiTreeNodeFlags_Framed", ImGuiTreeNodeFlags_Framed},
        {"ImGuiTreeNodeFlags_AllowOverlap", ImGuiTreeNodeFlags_AllowOverlap},
        {"ImGuiTreeNodeFlags_NoTreePushOnOpen", ImGuiTreeNodeFlags_NoTreePushOnOpen},
        {"ImGuiTreeNodeFlags_NoAutoOpenOnLog", ImGuiTreeNodeFlags_NoAutoOpenOnLog},
        {"ImGuiTreeNodeFlags_DefaultOpen", ImGuiTreeNodeFlags_DefaultOpen},
        {"ImGuiTreeNodeFlags_OpenOnDoubleClick", ImGuiTreeNodeFlags_OpenOnDoubleClick},
        {"ImGuiTreeNodeFlags_OpenOnArrow", ImGuiTreeNodeFlags_OpenOnArrow},
        {"ImGuiTreeNodeFlags_Leaf", ImGuiTreeNodeFlags_Leaf},
        {"ImGuiTreeNodeFlags_Bullet", ImGuiTreeNodeFlags_Bullet},
        {"ImGuiTreeNodeFlags_FramePadding", ImGuiTreeNodeFlags_FramePadding},
        {"ImGuiTreeNodeFlags_SpanAvailWidth", ImGuiTreeNodeFlags_SpanAvailWidth},
        {"ImGuiTreeNodeFlags_SpanFullWidth", ImGuiTreeNodeFlags_SpanFullWidth},
        {"ImGuiTreeNodeFlags_SpanLabelWidth", ImGuiTreeNodeFlags_SpanLabelWidth},
        {"ImGuiTreeNodeFlags_SpanAllColumns", ImGuiTreeNodeFlags_SpanAllColumns},
        {"ImGuiTreeNodeFlags_LabelSpanAllColumns", ImGuiTreeNodeFlags_LabelSpanAllColumns},
        {"ImGuiTreeNodeFlags_NavLeftJumpsToParent", ImGuiTreeNodeFlags_NavLeftJumpsToParent},
        {"ImGuiTreeNodeFlags_CollapsingHeader", ImGuiTreeNodeFlags_CollapsingHeader},
        {"ImGuiTreeNodeFlags_DrawLinesNone", ImGuiTreeNodeFlags_DrawLinesNone},
        {"ImGuiTreeNodeFlags_DrawLinesFull", ImGuiTreeNodeFlags_DrawLinesFull},
        {"ImGuiTreeNodeFlags_DrawLinesToNodes", ImGuiTreeNodeFlags_DrawLinesToNodes},
};

FlagEntry LuaGuiPopupFlags[] = {
        {"ImGuiPopupFlags_None", ImGuiPopupFlags_None},
        {"ImGuiPopupFlags_MouseButtonLeft", ImGuiPopupFlags_MouseButtonLeft},
        {"ImGuiPopupFlags_MouseButtonRight", ImGuiPopupFlags_MouseButtonRight},
        {"ImGuiPopupFlags_MouseButtonMiddle", ImGuiPopupFlags_MouseButtonMiddle},
        {"ImGuiPopupFlags_NoReopen", ImGuiPopupFlags_NoReopen},
        {"ImGuiPopupFlags_NoOpenOverExistingPopup", ImGuiPopupFlags_NoOpenOverExistingPopup},
        {"ImGuiPopupFlags_NoOpenOverItems", ImGuiPopupFlags_NoOpenOverItems},
        {"ImGuiPopupFlags_AnyPopupId", ImGuiPopupFlags_AnyPopupId},
        {"ImGuiPopupFlags_AnyPopupLevel", ImGuiPopupFlags_AnyPopupLevel},
        {"ImGuiPopupFlags_AnyPopup", ImGuiPopupFlags_AnyPopup},
};

FlagEntry LuaGuiSelectableFlags[] = {
        {"ImGuiSelectableFlags_None", ImGuiSelectableFlags_None},
        {"ImGuiSelectableFlags_NoAutoClosePopups", ImGuiSelectableFlags_NoAutoClosePopups},
        {"ImGuiSelectableFlags_SpanAllColumns", ImGuiSelectableFlags_SpanAllColumns},
        {"ImGuiSelectableFlags_AllowDoubleClick", ImGuiSelectableFlags_AllowDoubleClick},
        {"ImGuiSelectableFlags_Disabled", ImGuiSelectableFlags_Disabled},
        {"ImGuiSelectableFlags_AllowOverlap", ImGuiSelectableFlags_AllowOverlap},
        {"ImGuiSelectableFlags_Highlight", ImGuiSelectableFlags_Highlight},
};

FlagEntry LuaGuiComboFlags[] = {
        {"ImGuiComboFlags_None", ImGuiComboFlags_None},
        {"ImGuiComboFlags_PopupAlignLeft", ImGuiComboFlags_PopupAlignLeft},
        {"ImGuiComboFlags_HeightSmall", ImGuiComboFlags_HeightSmall},
        {"ImGuiComboFlags_HeightRegular", ImGuiComboFlags_HeightRegular},
        {"ImGuiComboFlags_HeightLarge", ImGuiComboFlags_HeightLarge},
        {"ImGuiComboFlags_HeightLargest", ImGuiComboFlags_HeightLargest},
        {"ImGuiComboFlags_NoArrowButton", ImGuiComboFlags_NoArrowButton},
        {"ImGuiComboFlags_NoPreview", ImGuiComboFlags_NoPreview},
        {"ImGuiComboFlags_WidthFitPreview", ImGuiComboFlags_WidthFitPreview},
};

FlagEntry LuaGuiTabBarFlags[] = {
        {"ImGuiTabBarFlags_None", ImGuiTabBarFlags_None},
        {"ImGuiTabBarFlags_Reorderable", ImGuiTabBarFlags_Reorderable},
        {"ImGuiTabBarFlags_AutoSelectNewTabs", ImGuiTabBarFlags_AutoSelectNewTabs},
        {"ImGuiTabBarFlags_TabListPopupButton", ImGuiTabBarFlags_TabListPopupButton},
        {"ImGuiTabBarFlags_NoCloseWithMiddleMouseButton", ImGuiTabBarFlags_NoCloseWithMiddleMouseButton},
        {"ImGuiTabBarFlags_NoTabListScrollingButtons", ImGuiTabBarFlags_NoTabListScrollingButtons},
        {"ImGuiTabBarFlags_NoTooltip", ImGuiTabBarFlags_NoTooltip},
        {"ImGuiTabBarFlags_DrawSelectedOverline", ImGuiTabBarFlags_DrawSelectedOverline},
        {"ImGuiTabBarFlags_FittingPolicyResizeDown", ImGuiTabBarFlags_FittingPolicyResizeDown},
        {"ImGuiTabBarFlags_FittingPolicyScroll", ImGuiTabBarFlags_FittingPolicyScroll},
};

FlagEntry LuaGuiTabItemFlags[] = {
        {"ImGuiTabItemFlags_None", ImGuiTabItemFlags_None},
        {"ImGuiTabItemFlags_UnsavedDocument", ImGuiTabItemFlags_UnsavedDocument},
        {"ImGuiTabItemFlags_SetSelected", ImGuiTabItemFlags_SetSelected},
        {"ImGuiTabItemFlags_NoCloseWithMiddleMouseButton", ImGuiTabItemFlags_NoCloseWithMiddleMouseButton},
        {"ImGuiTabItemFlags_NoPushId", ImGuiTabItemFlags_NoPushId},
        {"ImGuiTabItemFlags_NoTooltip", ImGuiTabItemFlags_NoTooltip},
        {"ImGuiTabItemFlags_NoReorder", ImGuiTabItemFlags_NoReorder},
        {"ImGuiTabItemFlags_Leading", ImGuiTabItemFlags_Leading},
        {"ImGuiTabItemFlags_Trailing", ImGuiTabItemFlags_Trailing},
        {"ImGuiTabItemFlags_NoAssumedClosure", ImGuiTabItemFlags_NoAssumedClosure},
};

FlagEntry LuaGuiFocusedFlags[] = {
        {"ImGuiFocusedFlags_None", ImGuiFocusedFlags_None},
        {"ImGuiFocusedFlags_ChildWindows", ImGuiFocusedFlags_ChildWindows},
        {"ImGuiFocusedFlags_RootWindow", ImGuiFocusedFlags_RootWindow},
        {"ImGuiFocusedFlags_AnyWindow", ImGuiFocusedFlags_AnyWindow},
        {"ImGuiFocusedFlags_NoPopupHierarchy", ImGuiFocusedFlags_NoPopupHierarchy},
        {"ImGuiFocusedFlags_RootAndChildWindows", ImGuiFocusedFlags_RootAndChildWindows},
};

FlagEntry LuaGuiHoveredFlags[] = {
        {"ImGuiHoveredFlags_None", ImGuiHoveredFlags_None},
        {"ImGuiHoveredFlags_ChildWindows", ImGuiHoveredFlags_ChildWindows},
        {"ImGuiHoveredFlags_RootWindow", ImGuiHoveredFlags_RootWindow},
        {"ImGuiHoveredFlags_AnyWindow", ImGuiHoveredFlags_AnyWindow},
        {"ImGuiHoveredFlags_NoPopupHierarchy", ImGuiHoveredFlags_NoPopupHierarchy},
        {"ImGuiHoveredFlags_AllowWhenBlockedByPopup", ImGuiHoveredFlags_AllowWhenBlockedByPopup},
        {"ImGuiHoveredFlags_AllowWhenBlockedByActiveItem", ImGuiHoveredFlags_AllowWhenBlockedByActiveItem},
        {"ImGuiHoveredFlags_AllowWhenOverlappedByItem", ImGuiHoveredFlags_AllowWhenOverlappedByItem},
        {"ImGuiHoveredFlags_AllowWhenOverlappedByWindow", ImGuiHoveredFlags_AllowWhenOverlappedByWindow},
        {"ImGuiHoveredFlags_AllowWhenDisabled", ImGuiHoveredFlags_AllowWhenDisabled},
        {"ImGuiHoveredFlags_NoNavOverride", ImGuiHoveredFlags_NoNavOverride},
        {"ImGuiHoveredFlags_AllowWhenOverlapped", ImGuiHoveredFlags_AllowWhenOverlapped},
        {"ImGuiHoveredFlags_RectOnly", ImGuiHoveredFlags_RectOnly},
        {"ImGuiHoveredFlags_RootAndChildWindows", ImGuiHoveredFlags_RootAndChildWindows},
        {"ImGuiHoveredFlags_ForTooltip", ImGuiHoveredFlags_ForTooltip},
        {"ImGuiHoveredFlags_Stationary", ImGuiHoveredFlags_Stationary},
        {"ImGuiHoveredFlags_DelayNone", ImGuiHoveredFlags_DelayNone},
        {"ImGuiHoveredFlags_DelayShort", ImGuiHoveredFlags_DelayShort},
        {"ImGuiHoveredFlags_DelayNormal", ImGuiHoveredFlags_DelayNormal},
        {"ImGuiHoveredFlags_NoSharedDelay", ImGuiHoveredFlags_NoSharedDelay},
};

FlagEntry LuaGuiDragDropFlags[] = {
        {"ImGuiDragDropFlags_None", ImGuiDragDropFlags_None},
        {"ImGuiDragDropFlags_SourceNoPreviewTooltip", ImGuiDragDropFlags_SourceNoPreviewTooltip},
        {"ImGuiDragDropFlags_SourceNoDisableHover", ImGuiDragDropFlags_SourceNoDisableHover},
        {"ImGuiDragDropFlags_SourceNoHoldToOpenOthers", ImGuiDragDropFlags_SourceNoHoldToOpenOthers},
        {"ImGuiDragDropFlags_SourceAllowNullID", ImGuiDragDropFlags_SourceAllowNullID},
        {"ImGuiDragDropFlags_SourceExtern", ImGuiDragDropFlags_SourceExtern},
        {"ImGuiDragDropFlags_PayloadAutoExpire", ImGuiDragDropFlags_PayloadAutoExpire},
        {"ImGuiDragDropFlags_PayloadNoCrossContext", ImGuiDragDropFlags_PayloadNoCrossContext},
        {"ImGuiDragDropFlags_PayloadNoCrossProcess", ImGuiDragDropFlags_PayloadNoCrossProcess},
        {"ImGuiDragDropFlags_AcceptBeforeDelivery", ImGuiDragDropFlags_AcceptBeforeDelivery},
        {"ImGuiDragDropFlags_AcceptNoDrawDefaultRect", ImGuiDragDropFlags_AcceptNoDrawDefaultRect},
        {"ImGuiDragDropFlags_AcceptNoPreviewTooltip", ImGuiDragDropFlags_AcceptNoPreviewTooltip},
        {"ImGuiDragDropFlags_AcceptPeekOnly", ImGuiDragDropFlags_AcceptPeekOnly},
};

FlagEntry LuaGuiDataType[] = {
        {"ImGuiDataType_S8", ImGuiDataType_S8},
        {"ImGuiDataType_U8", ImGuiDataType_U8},
        {"ImGuiDataType_S16", ImGuiDataType_S16},
        {"ImGuiDataType_U16", ImGuiDataType_U16},
        {"ImGuiDataType_S32", ImGuiDataType_S32},
        {"ImGuiDataType_U32", ImGuiDataType_U32},
        {"ImGuiDataType_S64", ImGuiDataType_S64},
        {"ImGuiDataType_U64", ImGuiDataType_U64},
        {"ImGuiDataType_Float", ImGuiDataType_Float},
        {"ImGuiDataType_Double", ImGuiDataType_Double},
        {"ImGuiDataType_Bool", ImGuiDataType_Bool},
        {"ImGuiDataType_String", ImGuiDataType_String},
        {"ImGuiDataType_COUNT", ImGuiDataType_COUNT},
};

FlagEntry LuaGuiDir[] = {
        {"ImGuiDir_None", ImGuiDir_None},
        {"ImGuiDir_Left", ImGuiDir_Left},
        {"ImGuiDir_Right", ImGuiDir_Right},
        {"ImGuiDir_Up", ImGuiDir_Up},
        {"ImGuiDir_Down", ImGuiDir_Down},
        {"ImGuiDir_COUNT", ImGuiDir_COUNT},
};

FlagEntry LuaGuiSortDirection[] = {
        {"ImGuiSortDirection_None", ImGuiSortDirection_None},
        {"ImGuiSortDirection_Ascending", ImGuiSortDirection_Ascending},
        {"ImGuiSortDirection_Descending", ImGuiSortDirection_Descending},
};

FlagEntry LuaGuiKey[] = {
        {"ImGuiKey_None", ImGuiKey_None},
        {"ImGuiKey_NamedKey_BEGIN", ImGuiKey_NamedKey_BEGIN},
        {"ImGuiKey_Tab", ImGuiKey_Tab},
        {"ImGuiKey_LeftArrow", ImGuiKey_LeftArrow},
        {"ImGuiKey_RightArrow", ImGuiKey_RightArrow},
        {"ImGuiKey_UpArrow", ImGuiKey_UpArrow},
        {"ImGuiKey_DownArrow", ImGuiKey_DownArrow},
        {"ImGuiKey_PageUp", ImGuiKey_PageUp},
        {"ImGuiKey_PageDown", ImGuiKey_PageDown},
        {"ImGuiKey_Home", ImGuiKey_Home},
        {"ImGuiKey_End", ImGuiKey_End},
        {"ImGuiKey_Insert", ImGuiKey_Insert},
        {"ImGuiKey_Delete", ImGuiKey_Delete},
        {"ImGuiKey_Backspace", ImGuiKey_Backspace},
        {"ImGuiKey_Space", ImGuiKey_Space},
        {"ImGuiKey_Enter", ImGuiKey_Enter},
        {"ImGuiKey_Escape", ImGuiKey_Escape},
        {"ImGuiKey_LeftCtrl", ImGuiKey_LeftCtrl},
        {"ImGuiKey_LeftShift", ImGuiKey_LeftShift},
        {"ImGuiKey_LeftAlt", ImGuiKey_LeftAlt},
        {"ImGuiKey_LeftSuper", ImGuiKey_LeftSuper},
        {"ImGuiKey_RightCtrl", ImGuiKey_RightCtrl},
        {"ImGuiKey_RightShift", ImGuiKey_RightShift},
        {"ImGuiKey_RightAlt", ImGuiKey_RightAlt},
        {"ImGuiKey_RightSuper", ImGuiKey_RightSuper},
        {"ImGuiKey_Menu", ImGuiKey_Menu},
        {"ImGuiKey_0", ImGuiKey_0},
        {"ImGuiKey_1", ImGuiKey_1},
        {"ImGuiKey_2", ImGuiKey_2},
        {"ImGuiKey_3", ImGuiKey_3},
        {"ImGuiKey_4", ImGuiKey_4},
        {"ImGuiKey_5", ImGuiKey_5},
        {"ImGuiKey_6", ImGuiKey_6},
        {"ImGuiKey_7", ImGuiKey_7},
        {"ImGuiKey_8", ImGuiKey_8},
        {"ImGuiKey_9", ImGuiKey_9},
        {"ImGuiKey_A", ImGuiKey_A},
        {"ImGuiKey_B", ImGuiKey_B},
        {"ImGuiKey_C", ImGuiKey_C},
        {"ImGuiKey_D", ImGuiKey_D},
        {"ImGuiKey_E", ImGuiKey_E},
        {"ImGuiKey_F", ImGuiKey_F},
        {"ImGuiKey_G", ImGuiKey_G},
        {"ImGuiKey_H", ImGuiKey_H},
        {"ImGuiKey_I", ImGuiKey_I},
        {"ImGuiKey_J", ImGuiKey_J},
        {"ImGuiKey_K", ImGuiKey_K},
        {"ImGuiKey_L", ImGuiKey_L},
        {"ImGuiKey_M", ImGuiKey_M},
        {"ImGuiKey_N", ImGuiKey_N},
        {"ImGuiKey_O", ImGuiKey_O},
        {"ImGuiKey_P", ImGuiKey_P},
        {"ImGuiKey_Q", ImGuiKey_Q},
        {"ImGuiKey_R", ImGuiKey_R},
        {"ImGuiKey_S", ImGuiKey_S},
        {"ImGuiKey_T", ImGuiKey_T},
        {"ImGuiKey_U", ImGuiKey_U},
        {"ImGuiKey_V", ImGuiKey_V},
        {"ImGuiKey_W", ImGuiKey_W},
        {"ImGuiKey_X", ImGuiKey_X},
        {"ImGuiKey_Y", ImGuiKey_Y},
        {"ImGuiKey_Z", ImGuiKey_Z},
        {"ImGuiKey_F1", ImGuiKey_F1},
        {"ImGuiKey_F2", ImGuiKey_F2},
        {"ImGuiKey_F3", ImGuiKey_F3},
        {"ImGuiKey_F4", ImGuiKey_F4},
        {"ImGuiKey_F5", ImGuiKey_F5},
        {"ImGuiKey_F6", ImGuiKey_F6},
        {"ImGuiKey_F7", ImGuiKey_F7},
        {"ImGuiKey_F8", ImGuiKey_F8},
        {"ImGuiKey_F9", ImGuiKey_F9},
        {"ImGuiKey_F10", ImGuiKey_F10},
        {"ImGuiKey_F11", ImGuiKey_F11},
        {"ImGuiKey_F12", ImGuiKey_F12},
        {"ImGuiKey_F13", ImGuiKey_F13},
        {"ImGuiKey_F14", ImGuiKey_F14},
        {"ImGuiKey_F15", ImGuiKey_F15},
        {"ImGuiKey_F16", ImGuiKey_F16},
        {"ImGuiKey_F17", ImGuiKey_F17},
        {"ImGuiKey_F18", ImGuiKey_F18},
        {"ImGuiKey_F19", ImGuiKey_F19},
        {"ImGuiKey_F20", ImGuiKey_F20},
        {"ImGuiKey_F21", ImGuiKey_F21},
        {"ImGuiKey_F22", ImGuiKey_F22},
        {"ImGuiKey_F23", ImGuiKey_F23},
        {"ImGuiKey_F24", ImGuiKey_F24},
        {"ImGuiKey_Apostrophe", ImGuiKey_Apostrophe},
        {"ImGuiKey_Comma", ImGuiKey_Comma},
        {"ImGuiKey_Minus", ImGuiKey_Minus},
        {"ImGuiKey_Period", ImGuiKey_Period},
        {"ImGuiKey_Slash", ImGuiKey_Slash},
        {"ImGuiKey_Semicolon", ImGuiKey_Semicolon},
        {"ImGuiKey_Equal", ImGuiKey_Equal},
        {"ImGuiKey_LeftBracket", ImGuiKey_LeftBracket},
        {"ImGuiKey_Backslash", ImGuiKey_Backslash},
        {"ImGuiKey_RightBracket", ImGuiKey_RightBracket},
        {"ImGuiKey_GraveAccent", ImGuiKey_GraveAccent},
        {"ImGuiKey_CapsLock", ImGuiKey_CapsLock},
        {"ImGuiKey_ScrollLock", ImGuiKey_ScrollLock},
        {"ImGuiKey_NumLock", ImGuiKey_NumLock},
        {"ImGuiKey_PrintScreen", ImGuiKey_PrintScreen},
        {"ImGuiKey_Pause", ImGuiKey_Pause},
        {"ImGuiKey_Keypad0", ImGuiKey_Keypad0},
        {"ImGuiKey_Keypad1", ImGuiKey_Keypad1},
        {"ImGuiKey_Keypad2", ImGuiKey_Keypad2},
        {"ImGuiKey_Keypad3", ImGuiKey_Keypad3},
        {"ImGuiKey_Keypad4", ImGuiKey_Keypad4},
        {"ImGuiKey_Keypad5", ImGuiKey_Keypad5},
        {"ImGuiKey_Keypad6", ImGuiKey_Keypad6},
        {"ImGuiKey_Keypad7", ImGuiKey_Keypad7},
        {"ImGuiKey_Keypad8", ImGuiKey_Keypad8},
        {"ImGuiKey_Keypad9", ImGuiKey_Keypad9},
        {"ImGuiKey_KeypadDecimal", ImGuiKey_KeypadDecimal},
        {"ImGuiKey_KeypadDivide", ImGuiKey_KeypadDivide},
        {"ImGuiKey_KeypadMultiply", ImGuiKey_KeypadMultiply},
        {"ImGuiKey_KeypadSubtract", ImGuiKey_KeypadSubtract},
        {"ImGuiKey_KeypadAdd", ImGuiKey_KeypadAdd},
        {"ImGuiKey_KeypadEnter", ImGuiKey_KeypadEnter},
        {"ImGuiKey_KeypadEqual", ImGuiKey_KeypadEqual},
        {"ImGuiKey_AppBack", ImGuiKey_AppBack},
        {"ImGuiKey_AppForward", ImGuiKey_AppForward},
        {"ImGuiKey_Oem102", ImGuiKey_Oem102},
        {"ImGuiKey_GamepadStart", ImGuiKey_GamepadStart},
        {"ImGuiKey_GamepadBack", ImGuiKey_GamepadBack},
        {"ImGuiKey_GamepadFaceLeft", ImGuiKey_GamepadFaceLeft},
        {"ImGuiKey_GamepadFaceRight", ImGuiKey_GamepadFaceRight},
        {"ImGuiKey_GamepadFaceUp", ImGuiKey_GamepadFaceUp},
        {"ImGuiKey_GamepadFaceDown", ImGuiKey_GamepadFaceDown},
        {"ImGuiKey_GamepadDpadLeft", ImGuiKey_GamepadDpadLeft},
        {"ImGuiKey_GamepadDpadRight", ImGuiKey_GamepadDpadRight},
        {"ImGuiKey_GamepadDpadUp", ImGuiKey_GamepadDpadUp},
        {"ImGuiKey_GamepadDpadDown", ImGuiKey_GamepadDpadDown},
        {"ImGuiKey_GamepadL1", ImGuiKey_GamepadL1},
        {"ImGuiKey_GamepadR1", ImGuiKey_GamepadR1},
        {"ImGuiKey_GamepadL2", ImGuiKey_GamepadL2},
        {"ImGuiKey_GamepadR2", ImGuiKey_GamepadR2},
        {"ImGuiKey_GamepadL3", ImGuiKey_GamepadL3},
        {"ImGuiKey_GamepadR3", ImGuiKey_GamepadR3},
        {"ImGuiKey_GamepadLStickLeft", ImGuiKey_GamepadLStickLeft},
        {"ImGuiKey_GamepadLStickRight", ImGuiKey_GamepadLStickRight},
        {"ImGuiKey_GamepadLStickUp", ImGuiKey_GamepadLStickUp},
        {"ImGuiKey_GamepadLStickDown", ImGuiKey_GamepadLStickDown},
        {"ImGuiKey_GamepadRStickLeft", ImGuiKey_GamepadRStickLeft},
        {"ImGuiKey_GamepadRStickRight", ImGuiKey_GamepadRStickRight},
        {"ImGuiKey_GamepadRStickUp", ImGuiKey_GamepadRStickUp},
        {"ImGuiKey_GamepadRStickDown", ImGuiKey_GamepadRStickDown},
        {"ImGuiKey_MouseLeft", ImGuiKey_MouseLeft},
        {"ImGuiKey_MouseRight", ImGuiKey_MouseRight},
        {"ImGuiKey_MouseMiddle", ImGuiKey_MouseMiddle},
        {"ImGuiKey_MouseX1", ImGuiKey_MouseX1},
        {"ImGuiKey_MouseX2", ImGuiKey_MouseX2},
        {"ImGuiKey_MouseWheelX", ImGuiKey_MouseWheelX},
        {"ImGuiKey_MouseWheelY", ImGuiKey_MouseWheelY},
        {"ImGuiKey_ReservedForModCtrl", ImGuiKey_ReservedForModCtrl},
        {"ImGuiKey_ReservedForModShift", ImGuiKey_ReservedForModShift},
        {"ImGuiKey_ReservedForModAlt", ImGuiKey_ReservedForModAlt},
        {"ImGuiKey_ReservedForModSuper", ImGuiKey_ReservedForModSuper},
        {"ImGuiKey_NamedKey_END", ImGuiKey_NamedKey_END},
        {"ImGuiKey_NamedKey_COUNT", ImGuiKey_NamedKey_COUNT},
        {"ImGuiMod_None", ImGuiMod_None},
        {"ImGuiMod_Ctrl", ImGuiMod_Ctrl},
        {"ImGuiMod_Shift", ImGuiMod_Shift},
        {"ImGuiMod_Alt", ImGuiMod_Alt},
        {"ImGuiMod_Super", ImGuiMod_Super},
        {"ImGuiMod_Mask_", ImGuiMod_Mask_},
};

FlagEntry LuaGuiInputFlags[] = {
        {"ImGuiInputFlags_None", ImGuiInputFlags_None},
        {"ImGuiInputFlags_Repeat", ImGuiInputFlags_Repeat},
        {"ImGuiInputFlags_RouteActive", ImGuiInputFlags_RouteActive},
        {"ImGuiInputFlags_RouteFocused", ImGuiInputFlags_RouteFocused},
        {"ImGuiInputFlags_RouteGlobal", ImGuiInputFlags_RouteGlobal},
        {"ImGuiInputFlags_RouteAlways", ImGuiInputFlags_RouteAlways},
        {"ImGuiInputFlags_RouteOverFocused", ImGuiInputFlags_RouteOverFocused},
        {"ImGuiInputFlags_RouteOverActive", ImGuiInputFlags_RouteOverActive},
        {"ImGuiInputFlags_RouteUnlessBgFocused", ImGuiInputFlags_RouteUnlessBgFocused},
        {"ImGuiInputFlags_RouteFromRootWindow", ImGuiInputFlags_RouteFromRootWindow},
        {"ImGuiInputFlags_Tooltip", ImGuiInputFlags_Tooltip},
};

FlagEntry LuaGuiConfigFlags[] = {
        {"ImGuiConfigFlags_None", ImGuiConfigFlags_None},
        {"ImGuiConfigFlags_NavEnableKeyboard", ImGuiConfigFlags_NavEnableKeyboard},
        {"ImGuiConfigFlags_NavEnableGamepad", ImGuiConfigFlags_NavEnableGamepad},
        {"ImGuiConfigFlags_NoMouse", ImGuiConfigFlags_NoMouse},
        {"ImGuiConfigFlags_NoMouseCursorChange", ImGuiConfigFlags_NoMouseCursorChange},
        {"ImGuiConfigFlags_NoKeyboard", ImGuiConfigFlags_NoKeyboard},
        {"ImGuiConfigFlags_IsSRGB", ImGuiConfigFlags_IsSRGB},
        {"ImGuiConfigFlags_IsTouchScreen", ImGuiConfigFlags_IsTouchScreen},
#ifndef IMGUI_DISABLE_OBSOLETE_FUNCTIONS
        {"ImGuiConfigFlags_NavEnableSetMousePos", ImGuiConfigFlags_NavEnableSetMousePos},
        {"ImGuiConfigFlags_NavNoCaptureKeyboard", ImGuiConfigFlags_NavNoCaptureKeyboard},
#endif
};

FlagEntry LuaGuiBackendFlags[] = {
        {"ImGuiBackendFlags_None", ImGuiBackendFlags_None},
        {"ImGuiBackendFlags_HasGamepad", ImGuiBackendFlags_HasGamepad},
        {"ImGuiBackendFlags_HasMouseCursors", ImGuiBackendFlags_HasMouseCursors},
        {"ImGuiBackendFlags_HasSetMousePos", ImGuiBackendFlags_HasSetMousePos},
        {"ImGuiBackendFlags_RendererHasVtxOffset", ImGuiBackendFlags_RendererHasVtxOffset},
        {"ImGuiBackendFlags_RendererHasTextures", ImGuiBackendFlags_RendererHasTextures},
};

FlagEntry LuaGuiCol[] = {
        {"ImGuiCol_Text", ImGuiCol_Text},
        {"ImGuiCol_TextDisabled", ImGuiCol_TextDisabled},
        {"ImGuiCol_WindowBg", ImGuiCol_WindowBg},
        {"ImGuiCol_ChildBg", ImGuiCol_ChildBg},
        {"ImGuiCol_PopupBg", ImGuiCol_PopupBg},
        {"ImGuiCol_Border", ImGuiCol_Border},
        {"ImGuiCol_BorderShadow", ImGuiCol_BorderShadow},
        {"ImGuiCol_FrameBg", ImGuiCol_FrameBg},
        {"ImGuiCol_FrameBgHovered", ImGuiCol_FrameBgHovered},
        {"ImGuiCol_FrameBgActive", ImGuiCol_FrameBgActive},
        {"ImGuiCol_TitleBg", ImGuiCol_TitleBg},
        {"ImGuiCol_TitleBgActive", ImGuiCol_TitleBgActive},
        {"ImGuiCol_TitleBgCollapsed", ImGuiCol_TitleBgCollapsed},
        {"ImGuiCol_MenuBarBg", ImGuiCol_MenuBarBg},
        {"ImGuiCol_ScrollbarBg", ImGuiCol_ScrollbarBg},
        {"ImGuiCol_ScrollbarGrab", ImGuiCol_ScrollbarGrab},
        {"ImGuiCol_ScrollbarGrabHovered", ImGuiCol_ScrollbarGrabHovered},
        {"ImGuiCol_ScrollbarGrabActive", ImGuiCol_ScrollbarGrabActive},
        {"ImGuiCol_CheckMark", ImGuiCol_CheckMark},
        {"ImGuiCol_SliderGrab", ImGuiCol_SliderGrab},
        {"ImGuiCol_SliderGrabActive", ImGuiCol_SliderGrabActive},
        {"ImGuiCol_Button", ImGuiCol_Button},
        {"ImGuiCol_ButtonHovered", ImGuiCol_ButtonHovered},
        {"ImGuiCol_ButtonActive", ImGuiCol_ButtonActive},
        {"ImGuiCol_Header", ImGuiCol_Header},
        {"ImGuiCol_HeaderHovered", ImGuiCol_HeaderHovered},
        {"ImGuiCol_HeaderActive", ImGuiCol_HeaderActive},
        {"ImGuiCol_Separator", ImGuiCol_Separator},
        {"ImGuiCol_SeparatorHovered", ImGuiCol_SeparatorHovered},
        {"ImGuiCol_SeparatorActive", ImGuiCol_SeparatorActive},
        {"ImGuiCol_ResizeGrip", ImGuiCol_ResizeGrip},
        {"ImGuiCol_ResizeGripHovered", ImGuiCol_ResizeGripHovered},
        {"ImGuiCol_ResizeGripActive", ImGuiCol_ResizeGripActive},
        {"ImGuiCol_InputTextCursor", ImGuiCol_InputTextCursor},
        {"ImGuiCol_TabHovered", ImGuiCol_TabHovered},
        {"ImGuiCol_Tab", ImGuiCol_Tab},
        {"ImGuiCol_TabSelected", ImGuiCol_TabSelected},
        {"ImGuiCol_TabSelectedOverline", ImGuiCol_TabSelectedOverline},
        {"ImGuiCol_TabDimmed", ImGuiCol_TabDimmed},
        {"ImGuiCol_TabDimmedSelected", ImGuiCol_TabDimmedSelected},
        {"ImGuiCol_TabDimmedSelectedOverline", ImGuiCol_TabDimmedSelectedOverline},
        {"ImGuiCol_PlotLines", ImGuiCol_PlotLines},
        {"ImGuiCol_PlotLinesHovered", ImGuiCol_PlotLinesHovered},
        {"ImGuiCol_PlotHistogram", ImGuiCol_PlotHistogram},
        {"ImGuiCol_PlotHistogramHovered", ImGuiCol_PlotHistogramHovered},
        {"ImGuiCol_TableHeaderBg", ImGuiCol_TableHeaderBg},
        {"ImGuiCol_TableBorderStrong", ImGuiCol_TableBorderStrong},
        {"ImGuiCol_TableBorderLight", ImGuiCol_TableBorderLight},
        {"ImGuiCol_TableRowBg", ImGuiCol_TableRowBg},
        {"ImGuiCol_TableRowBgAlt", ImGuiCol_TableRowBgAlt},
        {"ImGuiCol_TextLink", ImGuiCol_TextLink},
        {"ImGuiCol_TextSelectedBg", ImGuiCol_TextSelectedBg},
        {"ImGuiCol_TreeLines", ImGuiCol_TreeLines},
        {"ImGuiCol_DragDropTarget", ImGuiCol_DragDropTarget},
        {"ImGuiCol_NavCursor", ImGuiCol_NavCursor},
        {"ImGuiCol_NavWindowingHighlight", ImGuiCol_NavWindowingHighlight},
        {"ImGuiCol_NavWindowingDimBg", ImGuiCol_NavWindowingDimBg},
        {"ImGuiCol_ModalWindowDimBg", ImGuiCol_ModalWindowDimBg},
        {"ImGuiCol_COUNT", ImGuiCol_COUNT},
#ifndef IMGUI_DISABLE_OBSOLETE_FUNCTIONS
        {"ImGuiCol_TabActive", ImGuiCol_TabActive},
        {"ImGuiCol_TabUnfocused", ImGuiCol_TabUnfocused},
        {"ImGuiCol_TabUnfocusedActive", ImGuiCol_TabUnfocusedActive},
        {"ImGuiCol_NavHighlight", ImGuiCol_NavHighlight},
#endif
};

FlagEntry LuaGuiStyleVar[] = {
        {"ImGuiStyleVar_Alpha", ImGuiStyleVar_Alpha},
        {"ImGuiStyleVar_DisabledAlpha", ImGuiStyleVar_DisabledAlpha},
        {"ImGuiStyleVar_WindowPadding", ImGuiStyleVar_WindowPadding},
        {"ImGuiStyleVar_WindowRounding", ImGuiStyleVar_WindowRounding},
        {"ImGuiStyleVar_WindowBorderSize", ImGuiStyleVar_WindowBorderSize},
        {"ImGuiStyleVar_WindowMinSize", ImGuiStyleVar_WindowMinSize},
        {"ImGuiStyleVar_WindowTitleAlign", ImGuiStyleVar_WindowTitleAlign},
        {"ImGuiStyleVar_ChildRounding", ImGuiStyleVar_ChildRounding},
        {"ImGuiStyleVar_ChildBorderSize", ImGuiStyleVar_ChildBorderSize},
        {"ImGuiStyleVar_PopupRounding", ImGuiStyleVar_PopupRounding},
        {"ImGuiStyleVar_PopupBorderSize", ImGuiStyleVar_PopupBorderSize},
        {"ImGuiStyleVar_FramePadding", ImGuiStyleVar_FramePadding},
        {"ImGuiStyleVar_FrameRounding", ImGuiStyleVar_FrameRounding},
        {"ImGuiStyleVar_FrameBorderSize", ImGuiStyleVar_FrameBorderSize},
        {"ImGuiStyleVar_ItemSpacing", ImGuiStyleVar_ItemSpacing},
        {"ImGuiStyleVar_ItemInnerSpacing", ImGuiStyleVar_ItemInnerSpacing},
        {"ImGuiStyleVar_IndentSpacing", ImGuiStyleVar_IndentSpacing},
        {"ImGuiStyleVar_CellPadding", ImGuiStyleVar_CellPadding},
        {"ImGuiStyleVar_ScrollbarSize", ImGuiStyleVar_ScrollbarSize},
        {"ImGuiStyleVar_ScrollbarRounding", ImGuiStyleVar_ScrollbarRounding},
        {"ImGuiStyleVar_GrabMinSize", ImGuiStyleVar_GrabMinSize},
        {"ImGuiStyleVar_GrabRounding", ImGuiStyleVar_GrabRounding},
        {"ImGuiStyleVar_ImageBorderSize", ImGuiStyleVar_ImageBorderSize},
        {"ImGuiStyleVar_TabRounding", ImGuiStyleVar_TabRounding},
        {"ImGuiStyleVar_TabBorderSize", ImGuiStyleVar_TabBorderSize},
        {"ImGuiStyleVar_TabBarBorderSize", ImGuiStyleVar_TabBarBorderSize},
        {"ImGuiStyleVar_TabBarOverlineSize", ImGuiStyleVar_TabBarOverlineSize},
        {"ImGuiStyleVar_TableAngledHeadersAngle", ImGuiStyleVar_TableAngledHeadersAngle},
        {"ImGuiStyleVar_TableAngledHeadersTextAlign", ImGuiStyleVar_TableAngledHeadersTextAlign},
        {"ImGuiStyleVar_TreeLinesSize", ImGuiStyleVar_TreeLinesSize},
        {"ImGuiStyleVar_TreeLinesRounding", ImGuiStyleVar_TreeLinesRounding},
        {"ImGuiStyleVar_ButtonTextAlign", ImGuiStyleVar_ButtonTextAlign},
        {"ImGuiStyleVar_SelectableTextAlign", ImGuiStyleVar_SelectableTextAlign},
        {"ImGuiStyleVar_SeparatorTextBorderSize", ImGuiStyleVar_SeparatorTextBorderSize},
        {"ImGuiStyleVar_SeparatorTextAlign", ImGuiStyleVar_SeparatorTextAlign},
        {"ImGuiStyleVar_SeparatorTextPadding", ImGuiStyleVar_SeparatorTextPadding},
        {"ImGuiStyleVar_COUNT", ImGuiStyleVar_COUNT},
};

FlagEntry LuaGuiButtonFlags[] = {
        {"ImGuiButtonFlags_None", ImGuiButtonFlags_None},
        {"ImGuiButtonFlags_MouseButtonLeft", ImGuiButtonFlags_MouseButtonLeft},
        {"ImGuiButtonFlags_MouseButtonRight", ImGuiButtonFlags_MouseButtonRight},
        {"ImGuiButtonFlags_MouseButtonMiddle", ImGuiButtonFlags_MouseButtonMiddle},
        {"ImGuiButtonFlags_MouseButtonMask_", ImGuiButtonFlags_MouseButtonMask_},
        {"ImGuiButtonFlags_EnableNav", ImGuiButtonFlags_EnableNav},
};

FlagEntry LuaGuiColorEditFlags[] = {
        {"ImGuiColorEditFlags_None", ImGuiColorEditFlags_None},
        {"ImGuiColorEditFlags_NoAlpha", ImGuiColorEditFlags_NoAlpha},
        {"ImGuiColorEditFlags_NoPicker", ImGuiColorEditFlags_NoPicker},
        {"ImGuiColorEditFlags_NoOptions", ImGuiColorEditFlags_NoOptions},
        {"ImGuiColorEditFlags_NoSmallPreview", ImGuiColorEditFlags_NoSmallPreview},
        {"ImGuiColorEditFlags_NoInputs", ImGuiColorEditFlags_NoInputs},
        {"ImGuiColorEditFlags_NoTooltip", ImGuiColorEditFlags_NoTooltip},
        {"ImGuiColorEditFlags_NoLabel", ImGuiColorEditFlags_NoLabel},
        {"ImGuiColorEditFlags_NoSidePreview", ImGuiColorEditFlags_NoSidePreview},
        {"ImGuiColorEditFlags_NoDragDrop", ImGuiColorEditFlags_NoDragDrop},
        {"ImGuiColorEditFlags_NoBorder", ImGuiColorEditFlags_NoBorder},
        {"ImGuiColorEditFlags_AlphaOpaque", ImGuiColorEditFlags_AlphaOpaque},
        {"ImGuiColorEditFlags_AlphaNoBg", ImGuiColorEditFlags_AlphaNoBg},
        {"ImGuiColorEditFlags_AlphaPreviewHalf", ImGuiColorEditFlags_AlphaPreviewHalf},
        {"ImGuiColorEditFlags_AlphaBar", ImGuiColorEditFlags_AlphaBar},
        {"ImGuiColorEditFlags_HDR", ImGuiColorEditFlags_HDR},
        {"ImGuiColorEditFlags_DisplayRGB", ImGuiColorEditFlags_DisplayRGB},
        {"ImGuiColorEditFlags_DisplayHSV", ImGuiColorEditFlags_DisplayHSV},
        {"ImGuiColorEditFlags_DisplayHex", ImGuiColorEditFlags_DisplayHex},
        {"ImGuiColorEditFlags_Uint8", ImGuiColorEditFlags_Uint8},
        {"ImGuiColorEditFlags_Float", ImGuiColorEditFlags_Float},
        {"ImGuiColorEditFlags_PickerHueBar", ImGuiColorEditFlags_PickerHueBar},
        {"ImGuiColorEditFlags_PickerHueWheel", ImGuiColorEditFlags_PickerHueWheel},
        {"ImGuiColorEditFlags_InputRGB", ImGuiColorEditFlags_InputRGB},
        {"ImGuiColorEditFlags_InputHSV", ImGuiColorEditFlags_InputHSV},
        {"ImGuiColorEditFlags_DefaultOptions_", ImGuiColorEditFlags_DefaultOptions_},
        {"ImGuiColorEditFlags_AlphaMask_", ImGuiColorEditFlags_AlphaMask_},
        {"ImGuiColorEditFlags_DisplayMask_", ImGuiColorEditFlags_DisplayMask_},
        {"ImGuiColorEditFlags_DataTypeMask_", ImGuiColorEditFlags_DataTypeMask_},
        {"ImGuiColorEditFlags_PickerMask_", ImGuiColorEditFlags_PickerMask_},
        {"ImGuiColorEditFlags_InputMask_", ImGuiColorEditFlags_InputMask_},
#ifndef IMGUI_DISABLE_OBSOLETE_FUNCTIONS
        {"ImGuiColorEditFlags_AlphaPreview", ImGuiColorEditFlags_AlphaPreview},
#endif
};

FlagEntry LuaGuiSliderFlags[] = {
        {"ImGuiSliderFlags_None", ImGuiSliderFlags_None},
        {"ImGuiSliderFlags_Logarithmic", ImGuiSliderFlags_Logarithmic},
        {"ImGuiSliderFlags_NoRoundToFormat", ImGuiSliderFlags_NoRoundToFormat},
        {"ImGuiSliderFlags_NoInput", ImGuiSliderFlags_NoInput},
        {"ImGuiSliderFlags_WrapAround", ImGuiSliderFlags_WrapAround},
        {"ImGuiSliderFlags_ClampOnInput", ImGuiSliderFlags_ClampOnInput},
        {"ImGuiSliderFlags_ClampZeroRange", ImGuiSliderFlags_ClampZeroRange},
        {"ImGuiSliderFlags_NoSpeedTweaks", ImGuiSliderFlags_NoSpeedTweaks},
        {"ImGuiSliderFlags_AlwaysClamp", ImGuiSliderFlags_AlwaysClamp},
        {"ImGuiSliderFlags_InvalidMask_", ImGuiSliderFlags_InvalidMask_},
};

FlagEntry LuaGuiMouseButton[] = {
        {"ImGuiMouseButton_Left", ImGuiMouseButton_Left},
        {"ImGuiMouseButton_Right", ImGuiMouseButton_Right},
        {"ImGuiMouseButton_Middle", ImGuiMouseButton_Middle},
        {"ImGuiMouseButton_COUNT", ImGuiMouseButton_COUNT},
};

FlagEntry LuaGuiMouseCursor[] = {
        {"ImGuiMouseCursor_None", ImGuiMouseCursor_None},
        {"ImGuiMouseCursor_Arrow", ImGuiMouseCursor_Arrow},
        {"ImGuiMouseCursor_TextInput", ImGuiMouseCursor_TextInput},
        {"ImGuiMouseCursor_ResizeAll", ImGuiMouseCursor_ResizeAll},
        {"ImGuiMouseCursor_ResizeNS", ImGuiMouseCursor_ResizeNS},
        {"ImGuiMouseCursor_ResizeEW", ImGuiMouseCursor_ResizeEW},
        {"ImGuiMouseCursor_ResizeNESW", ImGuiMouseCursor_ResizeNESW},
        {"ImGuiMouseCursor_ResizeNWSE", ImGuiMouseCursor_ResizeNWSE},
        {"ImGuiMouseCursor_Hand", ImGuiMouseCursor_Hand},
        {"ImGuiMouseCursor_Wait", ImGuiMouseCursor_Wait},
        {"ImGuiMouseCursor_Progress", ImGuiMouseCursor_Progress},
        {"ImGuiMouseCursor_NotAllowed", ImGuiMouseCursor_NotAllowed},
        {"ImGuiMouseCursor_COUNT", ImGuiMouseCursor_COUNT},
};

FlagEntry LuaGuiMouseSource[] = {
        {"ImGuiMouseSource_Mouse", ImGuiMouseSource_Mouse},
        {"ImGuiMouseSource_TouchScreen", ImGuiMouseSource_TouchScreen},
        {"ImGuiMouseSource_Pen", ImGuiMouseSource_Pen},
        {"ImGuiMouseSource_COUNT", ImGuiMouseSource_COUNT},
};

FlagEntry LuaGuiCond[] = {
        {"ImGuiCond_None", ImGuiCond_None},
        {"ImGuiCond_Always", ImGuiCond_Always},
        {"ImGuiCond_Once", ImGuiCond_Once},
        {"ImGuiCond_FirstUseEver", ImGuiCond_FirstUseEver},
        {"ImGuiCond_Appearing", ImGuiCond_Appearing},
};

FlagEntry LuaGuiTableFlags[] = {
        {"ImGuiTableFlags_None", ImGuiTableFlags_None},
        {"ImGuiTableFlags_Resizable", ImGuiTableFlags_Resizable},
        {"ImGuiTableFlags_Reorderable", ImGuiTableFlags_Reorderable},
        {"ImGuiTableFlags_Hideable", ImGuiTableFlags_Hideable},
        {"ImGuiTableFlags_Sortable", ImGuiTableFlags_Sortable},
        {"ImGuiTableFlags_NoSavedSettings", ImGuiTableFlags_NoSavedSettings},
        {"ImGuiTableFlags_ContextMenuInBody", ImGuiTableFlags_ContextMenuInBody},
        {"ImGuiTableFlags_RowBg", ImGuiTableFlags_RowBg},
        {"ImGuiTableFlags_BordersInnerH", ImGuiTableFlags_BordersInnerH},
        {"ImGuiTableFlags_BordersOuterH", ImGuiTableFlags_BordersOuterH},
        {"ImGuiTableFlags_BordersInnerV", ImGuiTableFlags_BordersInnerV},
        {"ImGuiTableFlags_BordersOuterV", ImGuiTableFlags_BordersOuterV},
        {"ImGuiTableFlags_BordersH", ImGuiTableFlags_BordersH},
        {"ImGuiTableFlags_BordersV", ImGuiTableFlags_BordersV},
        {"ImGuiTableFlags_BordersInner", ImGuiTableFlags_BordersInner},
        {"ImGuiTableFlags_BordersOuter", ImGuiTableFlags_BordersOuter},
        {"ImGuiTableFlags_Borders", ImGuiTableFlags_Borders},
        {"ImGuiTableFlags_NoBordersInBody", ImGuiTableFlags_NoBordersInBody},
        {"ImGuiTableFlags_NoBordersInBodyUntilResize", ImGuiTableFlags_NoBordersInBodyUntilResize},
        {"ImGuiTableFlags_SizingFixedFit", ImGuiTableFlags_SizingFixedFit},
        {"ImGuiTableFlags_SizingFixedSame", ImGuiTableFlags_SizingFixedSame},
        {"ImGuiTableFlags_SizingStretchProp", ImGuiTableFlags_SizingStretchProp},
        {"ImGuiTableFlags_SizingStretchSame", ImGuiTableFlags_SizingStretchSame},
        {"ImGuiTableFlags_NoHostExtendX", ImGuiTableFlags_NoHostExtendX},
        {"ImGuiTableFlags_NoHostExtendY", ImGuiTableFlags_NoHostExtendY},
        {"ImGuiTableFlags_NoKeepColumnsVisible", ImGuiTableFlags_NoKeepColumnsVisible},
        {"ImGuiTableFlags_PreciseWidths", ImGuiTableFlags_PreciseWidths},
        {"ImGuiTableFlags_NoClip", ImGuiTableFlags_NoClip},
        {"ImGuiTableFlags_PadOuterX", ImGuiTableFlags_PadOuterX},
        {"ImGuiTableFlags_NoPadOuterX", ImGuiTableFlags_NoPadOuterX},
        {"ImGuiTableFlags_NoPadInnerX", ImGuiTableFlags_NoPadInnerX},
        {"ImGuiTableFlags_ScrollX", ImGuiTableFlags_ScrollX},
        {"ImGuiTableFlags_ScrollY", ImGuiTableFlags_ScrollY},
        {"ImGuiTableFlags_SortMulti", ImGuiTableFlags_SortMulti},
        {"ImGuiTableFlags_SortTristate", ImGuiTableFlags_SortTristate},
        {"ImGuiTableFlags_HighlightHoveredColumn", ImGuiTableFlags_HighlightHoveredColumn},
        {"ImGuiTableFlags_SizingMask_", ImGuiTableFlags_SizingMask_},
};

FlagEntry LuaGuiTableColumnFlags[] = {
        {"ImGuiTableColumnFlags_None", ImGuiTableColumnFlags_None},
        {"ImGuiTableColumnFlags_Disabled", ImGuiTableColumnFlags_Disabled},
        {"ImGuiTableColumnFlags_DefaultHide", ImGuiTableColumnFlags_DefaultHide},
        {"ImGuiTableColumnFlags_DefaultSort", ImGuiTableColumnFlags_DefaultSort},
        {"ImGuiTableColumnFlags_WidthStretch", ImGuiTableColumnFlags_WidthStretch},
        {"ImGuiTableColumnFlags_WidthFixed", ImGuiTableColumnFlags_WidthFixed},
        {"ImGuiTableColumnFlags_NoResize", ImGuiTableColumnFlags_NoResize},
        {"ImGuiTableColumnFlags_NoReorder", ImGuiTableColumnFlags_NoReorder},
        {"ImGuiTableColumnFlags_NoHide", ImGuiTableColumnFlags_NoHide},
        {"ImGuiTableColumnFlags_NoClip", ImGuiTableColumnFlags_NoClip},
        {"ImGuiTableColumnFlags_NoSort", ImGuiTableColumnFlags_NoSort},
        {"ImGuiTableColumnFlags_NoSortAscending", ImGuiTableColumnFlags_NoSortAscending},
        {"ImGuiTableColumnFlags_NoSortDescending", ImGuiTableColumnFlags_NoSortDescending},
        {"ImGuiTableColumnFlags_NoHeaderLabel", ImGuiTableColumnFlags_NoHeaderLabel},
        {"ImGuiTableColumnFlags_NoHeaderWidth", ImGuiTableColumnFlags_NoHeaderWidth},
        {"ImGuiTableColumnFlags_PreferSortAscending", ImGuiTableColumnFlags_PreferSortAscending},
        {"ImGuiTableColumnFlags_PreferSortDescending", ImGuiTableColumnFlags_PreferSortDescending},
        {"ImGuiTableColumnFlags_IndentEnable", ImGuiTableColumnFlags_IndentEnable},
        {"ImGuiTableColumnFlags_IndentDisable", ImGuiTableColumnFlags_IndentDisable},
        {"ImGuiTableColumnFlags_AngledHeader", ImGuiTableColumnFlags_AngledHeader},
        {"ImGuiTableColumnFlags_IsEnabled", ImGuiTableColumnFlags_IsEnabled},
        {"ImGuiTableColumnFlags_IsVisible", ImGuiTableColumnFlags_IsVisible},
        {"ImGuiTableColumnFlags_IsSorted", ImGuiTableColumnFlags_IsSorted},
        {"ImGuiTableColumnFlags_IsHovered", ImGuiTableColumnFlags_IsHovered},
        {"ImGuiTableColumnFlags_WidthMask_", ImGuiTableColumnFlags_WidthMask_},
        {"ImGuiTableColumnFlags_IndentMask_", ImGuiTableColumnFlags_IndentMask_},
        {"ImGuiTableColumnFlags_StatusMask_", ImGuiTableColumnFlags_StatusMask_},
        {"ImGuiTableColumnFlags_NoDirectResize_", ImGuiTableColumnFlags_NoDirectResize_},
};

FlagEntry LuaGuiTableRowFlags[] = {
        {"ImGuiTableRowFlags_None", ImGuiTableRowFlags_None},
        {"ImGuiTableRowFlags_Headers", ImGuiTableRowFlags_Headers},
};

FlagEntry LuaGuiTableBgTarget[] = {
        {"ImGuiTableBgTarget_None", ImGuiTableBgTarget_None},
        {"ImGuiTableBgTarget_RowBg0", ImGuiTableBgTarget_RowBg0},
        {"ImGuiTableBgTarget_RowBg1", ImGuiTableBgTarget_RowBg1},
        {"ImGuiTableBgTarget_CellBg", ImGuiTableBgTarget_CellBg},
};

void RegisterFlagsTable(lua_State *L,
                        const FlagEntry* entry,
                        const size_t count) {
    for (int i = 0; i < count; i++) {
        lua_pushnumber(L, entry[i].value);
        lua_setglobal(L, entry[i].name);
    }
}


void register_flags(lua_State* L) {
    RegisterFlagsTable(L, LuaGuiDataType, std::size(LuaGuiDataType));
    RegisterFlagsTable(L, LuaGuiDir, std::size(LuaGuiDir));
    RegisterFlagsTable(L, LuaGuiSortDirection, std::size(LuaGuiSortDirection));
    RegisterFlagsTable(L, LuaGuiKey, std::size(LuaGuiKey));
    RegisterFlagsTable(L, LuaGuiInputFlags, std::size(LuaGuiInputFlags));
    RegisterFlagsTable(L, LuaGuiConfigFlags, std::size(LuaGuiConfigFlags));
    RegisterFlagsTable(L, LuaGuiBackendFlags, std::size(LuaGuiBackendFlags));
    RegisterFlagsTable(L, LuaGuiCol, std::size(LuaGuiCol));
    RegisterFlagsTable(L, LuaGuiStyleVar, std::size(LuaGuiStyleVar));
    RegisterFlagsTable(L, LuaGuiButtonFlags, std::size(LuaGuiButtonFlags));
    RegisterFlagsTable(L, LuaGuiColorEditFlags, std::size(LuaGuiColorEditFlags));
    RegisterFlagsTable(L, LuaGuiSliderFlags, std::size(LuaGuiSliderFlags));
    RegisterFlagsTable(L, LuaGuiMouseButton, std::size(LuaGuiMouseButton));
    RegisterFlagsTable(L, LuaGuiMouseCursor, std::size(LuaGuiMouseCursor));
    RegisterFlagsTable(L, LuaGuiMouseSource, std::size(LuaGuiMouseSource));
    RegisterFlagsTable(L, LuaGuiCond, std::size(LuaGuiCond));
    RegisterFlagsTable(L, LuaGuiTableFlags, std::size(LuaGuiTableFlags));
    RegisterFlagsTable(L, LuaGuiTableColumnFlags, std::size(LuaGuiTableColumnFlags));
    RegisterFlagsTable(L, LuaGuiTableRowFlags, std::size(LuaGuiTableRowFlags));
    RegisterFlagsTable(L, LuaGuiTableBgTarget, std::size(LuaGuiTableBgTarget));
    RegisterFlagsTable(L, LuaGuiDragDropFlags, std::size(LuaGuiDragDropFlags));
    RegisterFlagsTable(L, LuaGuiWindowFlags, std::size(LuaGuiWindowFlags));
}

